language: crystal
install:
  - git clone https://github.com/libfann/fann.git
  - cd fann
  - cmake .
  - export CMAKE_INSTALL_PREFIX=/usr
  - sudo make install
  - cd ..
script: LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib crystal spec
notifications:
  email:
    recipients:
      - bar.hofesh@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
