language: crystal
install:
  - git clone https://github.com/libfann/fann.git
  - cd fann
  - cmake .
  - sudo make install
script: crystal spec
notifications:
  email:
    recipients:
      - bar.hofesh@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
